[project]
name = "download-estrategia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=2.0.0",
    "flask-socketio>=5.5.1",
    "logging>=0.4.9.6",
    "python-dotenv>=1.1.0",
    "selenium>=4.30.0",
]
